{{- if .Values.ingress.create }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "mlflow.fullname" . }}
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.hosts }}
  {{- $anyTlsHosts := false -}}
  {{- range .Values.ingress.hosts }}
  {{- if .tls }}
  {{- if .tls.enabled }}
  {{- $anyTlsHosts = true -}}
  {{- end }}
  {{- end }}
  {{- end }}
  {{- if $anyTlsHosts }}
  tls:
  {{- range .Values.ingress.hosts }}
  {{- if .tls }}
  {{- if .tls.enabled }}
    - hosts:
        - {{ .name | quote }}
      secretName: {{ .tls.secretName }}
  {{- end }}
  {{- end }}
  {{- end }}
  {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts | default (list .Values.ingress.host) }}
    - http:
        paths:
          - backend:
              service:
                name: {{ $.Release.Name }}
                port:
                  name: http
            {{- if $.Values.ingress.path }}
            path: {{ $.Values.ingress.path }}
            pathType: {{ $.Values.ingress.pathType }}
            {{- end }}
      host: {{ .name | quote }}
    {{- end }}
  {{- if .Values.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  {{- end }}
{{- end }}
