---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mlflow.fullname" . }}
type: Opaque
data:
  MLFLOW_BACKEND_STORE_URI:  {{ include "mlflow.db.connection" . | b64enc }}
  {{- if .Values.minio.enabled }}
  AWS_ACCESS_KEY_ID: {{ .Values.minio.auth.rootUser | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.minio.auth.rootPassword | b64enc }}
  {{- end }}
