{{- if (include "mlflow.secret.deploy" .) -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mlflow.fullname" . }}
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.backendStore.backendStoreUriExistingSecret | not }}
  MLFLOW_BACKEND_STORE_URI:  {{ include "mlflow.db.connection" . | trim | b64enc }}
  {{- end }}
  {{- if .Values.minio.enabled }}
  AWS_ACCESS_KEY_ID: {{ .Values.minio.auth.rootUser | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.minio.auth.rootPassword | b64enc }}
  {{- end }}
{{- end -}}
