---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mlflow.fullname" . }}-test-scripts
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
data:
{{- (.Files.Glob "test-scripts/*").AsConfig | nindent 2 }}
