---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mlflow.fullname" . }}
type: Opaque
data:
  MLFLOW_BACKEND_STORE_URI: {{ required "backendStore.backendStoreUri is required" .Values.backendStore.backendStoreUri | b64enc }}
